onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - runtime::mimir:
          script: |
            export classification;
            _ { $classification := "default"; }
      - grouper::bucket:
          buckets:
            default:
              rate: 250
      - render::json
      - offramp::file:
          file: {out}
