test:
  stage: test
  image: centos:7
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - yum install git make gcc clang openssl-static libstdc++-static autoconf bison  -y
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.31.0 -y
    - source $HOME/.cargo/env
    - rustup component add clippy
    - cargo build
    - cp target/debug/native/php-src/libs/* /lib64
    - cargo clippy
    - cargo test
    - make it
    - cd window
    - cargo clippy
    - cargo test
    - cd ../mimir
    - cargo clippy
    - cargo test

bench:
  stage: test
  image: centos:7
  when: always
  allow_failure: true
  cache:
    paths:
      - target
      - ~/.cargo/
  tags:
    - docker
  script:
    - yum install git make gcc clang openssl-static libstdc++-static autoconf bison  -y
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.31.0 -y
    - source $HOME/.cargo/env
    - cargo build --release
    - cp target/release/native/php-src/libs/* /lib64
    - make bench