
test:
  stage: test
  image: rust:1.28
  when: always
  tags:
    - docker
  script:
    - apt update 
    - apt install -y bison flex cmake automake
    - cargo test
    - make it
    - cd window
    - cargo test
   # - make clippy-install
   # - make clippy

