test:
  stage: test
  image: wayfair/tremor/dataeng-rust:1.33.0
  when: always
  # cache:
  #   paths:
  #     - target
  #     - .cargo
  tags:
    - docker
  script:
    - make chk_copyright_ci
    - make chk_unwrap_ci
    - source $HOME/.cargo/env
    - export CARGO_HOME=.cargo
    - cargo test --all-features
    - cargo test -p tremor-script -p window
    - cargo clippy --all-features
    - cp target/debug/native/php-src/libs/* /lib64
    - make it

# The bench server got claimed for something else :(
# doesn't make sense to run bench any more this way.
#
# bench:
#   stage: test
#   image: wayfair/tremor/dataeng-rust:1.31.1a
#   when: always
#   allow_failure: true
#   cache:
#     paths:
#       - target/
#   tags:
#     - docker
#   script: 
#     - source $HOME/.cargo/env
#     - cargo build --release
#     - cp target/release/native/php-src/libs/* /lib64
#     - make bench

# This job updates the live copy of the docs site
mkdocs:
  tags:  # this ensures it runs on the docs machine
    - docs
  script:
    - mkdocs build -d /docs/$CI_PROJECT_PATH
  only:
    - master


# This job creates/updates development copies of the site for every
# push to non-master branches
mkdocs-dev:
  tags:
    - docs
  script:
    - mkdir -p /docs/$CI_PROJECT_PATH/_dev/$CI_COMMIT_REF_NAME
    - mkdocs build -d /docs/$CI_PROJECT_PATH/_dev/$CI_COMMIT_REF_NAME
  except:
    - master

