test:
  stage: test
  image: centos:7
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - yum install git make gcc clang openssl-static libstdc++-static autoconf bison  -y
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.30.1 -y
    - source $HOME/.cargo/env
    - cargo build
    - cp target/debug/native/php-src/libs/* /lib64
    - cargo test
    - make it
    - cd window
    - cargo test

lint:
  stage: test
  image: centos:7
  when: always
  cache:
    paths:
      - target.clippy/
      - ~/.cargo/
  tags:
    - docker
  script:
    - yum install git make gcc clang openssl-static libstdc++-static autoconf bison -y
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
    - source $HOME/.cargo/env
    - cargo build
    - cp target/debug/native/php-src/libs/* /lib64
    - make clippy-install
    - make clippy

bench:
  stage: test
  image: centos:7
  when: always
  allow_failure: true
  cache:
    paths:
      - target
      - ~/.cargo/
  tags:
    - docker
  script:
    - yum install git make gcc clang openssl-static libstdc++-static autoconf bison  -y
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.30.1 -y
    - source $HOME/.cargo/env
    - cargo build --release
    - cp target/release/native/php-src/libs/* /lib64
    - make bench


mimir-test:
  stage: test
  image: rust:1.30
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - cd mimir
    - cargo test

mimir-lint:
  stage: test
  image: rust:1.30
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - cd mimir
    - rustup update
    - rustup install nightly
    - rustup component add clippy-preview --toolchain=nightly
    - CARGO_TARGET_DIR=target.clippy cargo +nightly clippy

mimir-bench:
  stage: test
  image: rust:1.30
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - cd mimir
    - apt update
    - apt-get -y install gnuplot
    - cargo bench
