test:
  stage: test
  image: rust:1.30
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - make check-vsn
    - apt update 
    - apt install -y bison flex cmake automake
    - cargo test
    - make it
    - cd window
    - cargo test

lint:
  stage: test
  image: rust:1.29
  when: always
  allow_failure: true
  cache:
    paths:
      - target.clippy/
      - ~/.cargo/
  tags:
    - docker
  script:
    - apt update 
    - apt install -y bison flex cmake automake
    - make clippy-install
    - make clippy


bench:
  stage: test
  image: rust:1.29
  when: always
  allow_failure: true
  cache:
    paths:
      - target
      - ~/.cargo/
  tags:
    - docker
  script:
    - apt update 
    - apt install -y bison flex cmake automake
    - make publish-bench
