test:
  stage: test
  image: wayfair/data-engineering/dataeng-rust:1.32.0
  when: always
  # cache:
  #   paths:
  #     - target
  #     - .cargo
  tags:
    - docker
  script:
    - source $HOME/.cargo/env
    - export CARGO_HOME=.cargo
    - cargo test
    - cargo test -p mimir -p window
    - cargo clippy
    - cargo build --features php-runtime
    - cp target/debug/native/php-src/libs/* /lib64
    - make it

# The bench server got claimed for something else :(
# doesn't make sense to run bench any more this way.
#
# bench:
#   stage: test
#   image: wayfair/data-engineering/dataeng-rust:1.31.1a
#   when: always
#   allow_failure: true
#   cache:
#     paths:
#       - target/
#   tags:
#     - docker
#   script: 
#     - source $HOME/.cargo/env
#     - cargo build --release
#     - cp target/release/native/php-src/libs/* /lib64
#     - make bench
