[package]
name = "tremor-runtime"
version = "0.2.0"
description = "Tremor Runtime"
authors = ["Heinz Gies <hgies@wayfair.com>", "Darach Ennis <dennis@wayfair.com>"]

[dependencies]
reqwest = "0.8"
futures = "0.1"
rand = "0.5"
clap = "2.23"
rdkafka = "0.17"
rdkafka-sys = "0.11.4-0"
log = "0.4"
env_logger = "0.5"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
prometheus = { version = "0.4", features = ["process"] }
lazy_static = "0.2"
elastic = "0.20"
elastic_derive = "0.20"
threadpool = "1.7.1"
hyper = "0.12"
chrono = "0.4"
regex = "1"
maplit = "1.0.1"


# tiberius = "0.3"
#tiberius = { version = "0.3", default-features=false, features=["chrono"] }
tiberius = { git = "https://github.com/Licenser/tiberius", branch="fixes", default-features=false, features=["chrono"] }
futures-state-stream = "0.1"
tokio = "0.1.8"
tokio-current-thread = "0.1.1"

window = { path = "window" }

mimir = { git = "https://gitlab+deploy-token-1:ZSysTyvMd8a-w-hVS7mn@git.csnzoo.com/data-engineering/mimir-rs.git", branch = "master" }
# mimir = { path = "../mimir-rs" }
hdrhistogram = "6.0.6"
xz2 = "0.1.5"
libc = "0.2.43"
spmc = "0.2.2"

[[bin]]
name = "tremor-runtime"
path = "src/main.rs"

[[bin]]
name = "tremor-runtime-bench"
path = "src/bench.rs"

[[bin]]
name = "mimir-tool"
path = "src/tool/main.rs"

[features]
default = []
try_spmc = []
