[package]
name = "tremor-runtime"
version = "0.3.5"
description = "Tremor Runtime"
authors = ["Heinz Gies <hgies@wayfair.com>", "Darach Ennis <dennis@wayfair.com>", "Colin Clark <colclark@wayfair.com>", "Cyndy Pooley <cpooley@wayfair.com>", "Ivan Monov <imonov@wayfair.com>", "Gordon Guthrie <gguthrie@wayfair.com>"]
edition = "2018"

[workspace]

members = [
    "mimir",
    "window",
]

[profile.release]
lto = true

[dependencies]
actix = "0.7"
actix-web = { version = "0.7", features = ["alpn"] }
base64 = "0.9"
bytes = "0.4"
chrono = "0.4"
clap = "2.23"
dot = "0.1.4"
elastic = "0.20"
elastic_derive = "0.20"
env_logger = "0.5"
error-chain="0.12"
futures = "0.1"
hdrhistogram = "6.0.6"
hostname = "0.1"
hyper = "0.12"
lazy_static = "0.2"
libc = "0.2.43"
log = "0.4"
maplit = "1.0"
openssl = { version="0.10" }
prometheus = { version = "0.4", features = ["process"] }
rand = "0.5"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
threadpool = "1.7.1"
tokio = "0.1.8"
uuid = { version = "0.7", features = ["serde", "v4"] }
window = { path = "window" }
mimir = { path = "mimir" }
xz2 = "0.1.5"

# php
php = { git = "https://github.com/Licenser/php-rs", branch = "master" }

# mssql
tiberius = { git = "https://github.com/Licenser/tiberius", branch="fixes", default-features=false, features=["chrono"], optional = true }
futures-state-stream = {version = "0.1", optional=true}
tokio-current-thread = {version = "0.1.1", optional=true}

# kafka
rdkafka = {version = "0.17", optional = true}
rdkafka-sys = {version = "0.11.4-0", optional = true}
tokio-threadpool = {version = "0.1.7", optional=true}

[dev-dependencies]
matches = "0.1.8"


[features]
default = ["mssql", "kafka"]
kafka = ["rdkafka", "rdkafka-sys", "tokio-threadpool"]
mssql = ["tiberius", "futures-state-stream", "tokio-current-thread"]
