[package]
name = "traffic-shaping-tool"
version = "0.1.0"
authors = ["Heinz Gies <hgies@wayfair.com>"]

[dependencies]
futures = "0.1"
rand = "0.5"
clap = "2.23"
rdkafka = "0.17"
rdkafka-sys = "0.11.4-0"
log = "0.4"
env_logger = "0.5"
serde_json = "1.0"

prometheus = "0.4"
lazy_static = "0.2.11"

hyper = "0.12"