onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - runtime::mimir:
          script: |
            export classification, dimensions;
            _ { $classification := "test"; $dimensions := [type, application]; }
      - grouper::bucket:
          buckets:
            test:
              rate: 1
      - render::json
      - offramp::file:
          file: {out}
