onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - runtime::mimir:
          script: |
            export classification;
            short_message:"INFO" { tremor.class := "info"; $classification := "info"; return; }
            short_message:"ERROR" { $classification := "error"; return; }
      - render::json
      - grouper::bucket:
          buckets:
            info:
              rate: 2
            error:
              rate: 3
      - offramp::file:
          file: {out}
