onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - classifier::mimir:
          rules:
            - rule: 'a:"b"'
              class: default
      - grouper::bucket:
          buckets:
            default:
              rate: 250
      - render::json
      - offramp::file:
          file: {out}
