apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tremor-runtime-applog
  labels:
    app: tremor-runtime
    topic: applog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tremor-runtime
      topic: applog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tremor-runtime
        topic: applog
    spec:
      containers:
      - env:
        - name: INPUT
          value: kafka
        - name: INPUT_CONFIG
          value: applog|kafkac4n1.dev.bo1.csnzoo.com:9092
        - name: OUTPUT
          value: kafka
        - name: OUTPUT_CONFIG
          value: tremor-applog|kafkac4n1.dev.bo1.csnzoo.com:9092
        - name: PARSER
          value: json
        - name: CLASSIFIER
          value: matcher
        - name: CLASSIFIER_CONFIG
          value: '[{"application=recsvc":"applog_recsvc"},{"application=sayl": "applog_sayl"},{"wf_index_type=applog_purest": "applog_purest"},{"wf_index_type=applog_admin": "applog_admin"},{"wf_index_type=applog_supply_chain_services": "applog_supply_chain_services"},{"wf_index_type=applog_logs": "applog_logs"},{"wf_index_type=syslog_haproxy": "syslog_haproxy"},{"wf_index_type=syslog_logs": "syslog_logs"},{"wf_index_type=syslog_influxdb": "syslog_influxdb"},{"wf_index_type=syslog_ftpd": "syslog_ftpd"},{"wf_index_type=syslog_hypernova": "syslog_hypernova"},{"wf_index_type=edilog": "edilog"},{"wf_index_type=sqlserverlog": "sqlserverlog"}]'
        - name: GROUPING
          value: bucket
        - name: GROUPING_CONFIG
          value: 'default:1|applog_recsvc:5000|applog_sayl:10000|applog_purest:75000|applog_admin:3000|applog_supply_chain_services:75000|applog_logs:18000|syslog_haproxy:10000|syslog_cisco:500|syslog_logs:7000|syslog_influxdb:7000|syslog_ftpd:30000|syslog_hypernova:500|edilog:15000|sqlserverlog:500'
        image: artifactory.service.bo1.csnzoo.com/wayfair/traffic-shaping-tool:0.1.4
        name: tremor-runtime-applog
        ports:
        - containerPort: 9898
          protocol: TCP
