apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tremor-runtime
  name: tremor-runtime
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tremor-runtime
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tremor-runtime
    spec:
      containers:
      - env:
        - name: INPUT
          value: kafka
        - name: INPUT_CONFIG
          value: '{"group_id":"demo","topics":["demo"],"brokers":["kafka:9092"]}'
        - name: OUTPUT
          value: es
        - name: OUTPUT_CONFIG
          value: '{"endpoints":["http://elastichotc3n1:9200"], "index":"demo","batch_size":300,"batch_timeout":100,"threads":5, "concurrency": 5, "backoff_rules": [50, 100, 250, 500, 1000, 5000, 10000]}'
        - name: PARSER
          value: json
        - name: CLASSIFIER
          value: mimir
        - name: CLASSIFIER_CONFIG
          value: '[{"application=recsvc":"applog_recsvc"},{"application=sayl": "applog_sayl"},{"wf_index_type=applog_purest":
            "applog_purest"},{"wf_index_type=applog_admin": "applog_admin"},{"wf_index_type=applog_supply_chain_services":
            "applog_supply_chain_services"},{"wf_index_type=applog_logs": "applog_logs"},{"wf_index_type=syslog_haproxy":
            "syslog_haproxy"},{"wf_index_type=syslog_logs": "syslog_logs"},{"wf_index_type=syslog_influxdb":
            "syslog_influxdb"},{"wf_index_type=syslog_ftpd": "syslog_ftpd"},{"wf_index_type=syslog_hypernova":
            "syslog_hypernova"},{"wf_index_type=edilog": "edilog"},{"wf_index_type=sqlserverlog":
            "sqlserverlog"},{"type=applog":"applog"}]'
        - name: GROUPING
          value: bucket
        - name: GROUPING_CONFIG
          value: '[{"name":"default","rate":1000},{"name":"applog_recsvc","rate":5000,"keys":["application"]},{"name":"applog_sayl","rate":10000,"keys":["application"]},{"name":"applog_purest","rate":75000,"keys":["logger_name"]},{"name":"applog_admin","rate":3000,"keys":["logger_name"]},{"name":"applog_supply_chain_services","rate":75000},{"name":"applog_logs","rate":18000,"keys":["application"]},{"name":"syslog_haproxy","rate":10000,"keys":["syslog_hostname"]},{"name":"syslog_cisco","rate":500,"keys":["src_ip","dst_ip"]},{"name":"syslog_logs","rate":7000,"keys":["syslog_hostname"]},{"name":"syslog_influxdb","rate":7000},{"name":"syslog_ftpd","rate":30000,"keys":["syslog_hostname"]},{"name":"syslog_hypernova","rate":500,"keys":["syslog_hostname"]},{"name":"edilog","rate":15000},{"name":"sqlserverlog","rate":500},{"name":"applog","rate":300,"keys":["application"]}]'
        image: artifactory.service.bo1.csnzoo.com/wayfair/data-engineering/tremor-runtime:0.1.12
        name: tremor-runtime
        ports:
        - containerPort: 9898
          protocol: TCP
