onramp:
  - id: metronome
    type: metronome
    config:
      interval: 10000
offramp:
  - id: stdout
    type: stdout
pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - outliers
    nodes: []
    links:
      in: [ out ]

binding:
  - id: default
    links:
      '/onramp/metronome/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/stdout/{instance}/in' ]
