[package]
name = "tremor-server"
version = "0.1.0"
authors = ["Darach Ennis <dennis@wayfair.com>"]
edition = "2018"

[dependencies]
tremor-runtime = { path = "../" }
tremor-api = { path = "../tremor-api" }
serde_yaml = "0.8"
clap = { version = "2", features = ["yaml"] }
env_logger = "0.6"
log = "0.4"
log4rs = "0.8"
actix-web = "1"
actix-files = "0.1"
actix-cors = "0.1"
mimalloc = { version = "*", default-features = false }


[features]
default = []
