---
onramps:
  - onramp::blaster:
      source: ./demo/data/data.json.xz
      pipeline: main

pipelines:
  - name: main
    subpipelines:
      - name: done
        steps:
    steps:
      - parse::json
      - runtime::mimir:
          script: |
            export classification, dimension, rate, index_type, below, timeframe;

            _ { $index_type := index; $below := 5; $timeframe := 10000; }

            application="app1" { $classification := "applog_app1"; $rate := 1250; }
            application="app2" { $classification := "applog_app2"; $rate := 2500; $below := 10; }
            application="app3" { $classification := "applog_app3"; $rate := 18750; }
            application="app4" { $classification := "applog_app4"; $rate := 750; $below := 10;   }
            application="app5" { $classification := "applog_app5"; $rate := 18750; }
            $classification { $dimension := application; return; }

            index_type="applog_app6" { $dimension := logger_name; $classification := "applog_app6"; $rate := 4500; return; }

            index_type="syslog_app1" { $classification := "syslog_app1"; $rate := 2500; }
            tags:"tag1" { $classification := "syslog_app2"; $rate := 125; }
            index_type="syslog_app3" { $classification := "syslog_app3"; $rate := 1750; }
            index_type="syslog_app4" { $classification := "syslog_app4"; $rate := 1750; }
            index_type="syslog_app5" { $classification := "syslog_app5"; $rate := 7500; }
            index_type="syslog_app6" { $classification := "syslog_app6"; $rate := 125; }
            $classification { $dimension := syslog_hostname; return; }

            _ { $classification := "default"; $rate := 250; }
      - render::json
      - grouper::bucket:
          buckets:
            applog_app1:
              rate: 1250
            applog_app2:
              rate: 2500
            applog_app3:
              rate: 18750
            applog_app4:
              rate: 750
            applog_app5:
              rate: 18750
            applog_app6:
              rate: 4500
            syslog_app1:
              rate: 2500
            syslog_app2:
              rate: 125
            syslog_app3:
              rate: 1750
            syslog_app4:
              rate: 1750
            syslog_app5:
              rate: 7500
            syslog_app6:
              rate: 125
            edilog:
              rate: 3750
            sqlserverlog:
              rate: 125
            applog:
              rate: 75
            default:
              rate: 250
      - offramp::blackhole:
          warmup_secs: 10
          stop_after_secs: 40
          significant_figures: 2
