# Test a realistic workflow including json encoding and decoding
# and connect both the pass and the overflow output to the
# blackhole to acount for the data
---
onramp:
  - id: blaster
    type: blaster
    codec: json
    config:
      source: ./demo/data/data.json.xz

offramp:
  - id: blackhole
    type: blackhole
    codec: json
    config:
      warmup_secs: 10
      stop_after_secs: 40
      significant_figures: 2


binding:
  - id: bench
    links:
      '/onramp/blaster/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/blackhole/{instance}/in' ]

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            # export class, dimension, rate, index_type;
            #
            # _ { $index_type := index; $app := application;}
            #
            #
            # $app="app1" { $class := "applog_app1"; $rate := 1250;  $dimension := $app; return; }
            # $app="app2" { $class := "applog_app2"; $rate := 2500;  $dimension := $app; return; }
            # $app="app3" { $class := "applog_app3"; $rate := 18750; $dimension := $app; return; }
            # $app="app4" { $class := "applog_app4"; $rate := 750;   $dimension := $app; return; }
            # $app="app5" { $class := "applog_app5"; $rate := 18750; $dimension := $app; return; }
            #
            #
            # _ { $it := index_type; } 

            # $it="applog_app6" { $class := "applog_app6"; $rate := 4500; $dimension := logger_name; return; }

            # $it="syslog_app1" { $class := "syslog_app1"; $rate := 2500; $dimension := syslog_hostname; return; }
            # tags:"tag1"       { $class := "syslog_app2"; $rate := 125;  $dimension := syslog_hostname; return; }
            # $it="syslog_app3" { $class := "syslog_app3"; $rate := 1750; $dimension := syslog_hostname; return; }
            # $it="syslog_app4" { $class := "syslog_app4"; $rate := 7500; $dimension := syslog_hostname; return; }
            # $it="syslog_app5" { $class := "syslog_app5"; $rate := 125;  $dimension := syslog_hostname; return; }
            # $it="syslog_app6" { $class := "syslog_app6"; $rate := 3750; $dimension := syslog_hostname; return; }
            #
            # _ { $class := "default"; $rate := 250; }
            match event.application of
              case "app1" => let $class = "applog_app1",  let $rate = 1250, let $dimension = event.application, emit event
              case "app2" => let $class = "applog_app1",  let $rate = 2500, let $dimension = event.application, emit event
              case "app3" => let $class = "applog_app1",  let $rate = 18750, let $dimension = event.application, emit event
              case "app4" => let $class = "applog_app1",  let $rate = 750, let $dimension = event.application, emit event
              case "app5" => let $class = "applog_app1",  let $rate = 18750, let $dimension = event.application, emit event
              default => null
            end;
            match event.index_type of
              case "applog_app6" => let $class = "applog_app6", let $rate = 4500, let $dimensions = event.logger_name, emit event
              case "syslog_app1" => let $class = "syslog_app1", let $rate = 2500, let $dimensions = event.syslog_hostname, emit event
              default => null
            end;
            match array::contains(event.tags, "tag1") of
              case true => let $class = "syslog_app2", let $rate = 125, let $dimensions = event.syslog_hostname, emit event
              default => null
            end;
            match event.index_type of
              case "syslog_app3" => let $class = "syslog_app3", let $rate = 1750, let $dimensions = event.syslog_hostname
              case "syslog_app4" => let $class = "syslog_app4", let $rate = 7500, let $dimensions = event.syslog_hostname
              case "syslog_app5" => let $class = "syslog_app5", let $rate = 125, let $dimensions = event.syslog_hostname
              case "syslog_app6" => let $class = "syslog_app6", let $rate = 3750, let $dimensions = event.syslog_hostname
              default => let $class = "default", let $rate = 250
            end;
            event;
      - id: group
        op: grouper::bucket
    links:
      in: [ runtime ]
      runtime: [ group ]
      group: [ out ]
      group/overflow: [ out ]
