---
deployments:
  - id: logging
    description: Filtering of applog and syslog streams
    bindings:
      onramps:
        - onramp::blaster:
            id: blaster
            source: ./demo/data/data.json.xz
      offramps:
        - offramp::blackhole:
            id: blackhole
            warmup_secs: 10
            stop_after_secs: 40
            significant_figures: 2
            
links:
  /deployments/logging/blaster: /pipelines/main/in
  /pipelines/main/out: /deployments/logging/out

pipelines:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - parse:
          type: parse::json
      - classify:
          type: runtime::mimir
          rules: |

            _ { $index_type := index }
            application="app1" { $classification := "applog_app1"; }
            application="app2" { $classification := "applog_app2"; }
            application="app3" { $classification := "applog_app3"; }
            application="app4" { $classification := "applog_app4"; }
            application="app5" { $classification := "applog_app5"; }
            $classification { $dimension := application; break; }

            index_type="applog_app6" { $dimension := logger_name; $classification := "applog_app6"; break; }

            index_type="syslog_app1" { $classification := "syslog_app1"; }
            tags:"tag1" { $classification := "syslog_app2"; }
            index_type="syslog_app2" { $classification := "syslog_app2"; }
            index_type="syslog_app3" { $classification := "syslog_app3"; }
            index_type="syslog_app4" { $classification := "syslog_app4"; }
            index_type="syslog_app5" { $classification := "syslog_app5"; }
            index_type="syslog_app6" { $classification := "syslog_app6"; }
            $classification { $dimension := syslog_hostname; break; }

            index_type="edilog" { $classification := "edilog"; $dimension := syslog_hostname; break; }
            index_type="sqlserverlog" { $classification := "sqlserverlog"; $dimension := [src_ip, dst_ip]; break; }
            type="applog" { $classification := "applog"; $dimension := [src_ip, dst_ip]; break; }
            _ { $classification := "default" }
      - bucket:
          type: grouper::bucket
          buckets:
            applog_app1:
              rate: 1250
            applog_app2:
              rate: 2500
            applog_app3:
              rate: 18750
            applog_app4:
              rate: 750
            applog_app5:
              rate: 18750
            applog_app6:
              rate: 4500
            syslog_app1:
              rate: 2500
            syslog_app2:
              rate: 125
            syslog_app3:
              rate: 1750
            syslog_app4:
              rate: 1750
            syslog_app5:
              rate: 7500
            syslog_app6:
              rate: 125
            edilog:
              rate: 3750
            sqlserverlog:
              rate: 125
            applog:
              rate: 75
            default:
              rate: 250
      - render:
        type: render::json
    links:
      parse: classify
      classify: done
      route/default: done
      application/out: done
      logger_name/out: done
      syslog_hostname/out: done
      ips/out: done
      done/out: bucket
      bucket/out: render
    imports:
      in: parse/in
    exports:
      out:
        - render/out
