onramp:
  - id: metronome
    type: metronome
    config:
      source: demo/data/data.json.xz
      interval: 500 # 2 events/s
    codec: json

offramp:
  - id: rest
    type: rest
    config:
      endpoints:
#        - http://127.0.0.1:8086/write?db=tremor
        - http://127.0.0.1:8080/write?db=tremor
      headers:
        'Content-Type': 'application/json'
    codec: influx
  - id: console
    type: stdout

pipeline:
  - id: demo
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: to_influx
        op: runtime::tremor
        config:
          script: |
            # fake a metric via transforming a periodic metronome event
            {
              "measurement": "test",
              "tags": {
                "host": system::hostname(),
              },
              "fields": {
                "random_value": random::integer(0,100)
              },
              "timestamp": event.ingest_ns
            }

    links:
      in: [ to_influx ]
      to_influx: [ out ]


binding:
  - id: default
    links:
      '/onramp/metronome/{instance}/out': [ '/pipeline/demo/{instance}/in' ]
      '/pipeline/demo/{instance}/out': [ '/offramp/rest/{instance}/in', '/offramp/console/{instance}/in'  ]

mapping:
  /binding/default/01:
    instance: 01
