[package]
name = "tremor-pipeline"
version = "0.1.0"
authors = ["Heinz Gies <hgies@wayfair.com>", "Darach Ennis <dennis@wayfair.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
hashbrown = { version = "0.1", features = ["serde"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
petgraph = "0.4"
error-chain="0.12"
tremor-script = { path = "../tremor-script" }
lazy_static = "1"
window = { path = "../window" }
indexmap = { version = "1", features=["serde-1"] }
lru = "0.1"
rmp-serde = "0.13"

[dev-dependencies]
#maplit = "1"
maplit = { git = "https://github.com/Licenser/maplit", branch="hashbrown", features=["hashbrown"] }
criterion = "0.2"
xz2 = "0.1"
base64 = "*"
jemallocator = "0.1"


[[bench]]
name = "distsys"
harness = false

