version: '3.3'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:2.11-1.1.0'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "demo:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  loadgen:
    image: tremor-runtime
    depends_on:
      - kafka
    environment:
      - SLEEP=30
      - CONFIG_FILE=/configs/loadgen-250.yaml
      - LOGGER_FILE=/configs/logger.yaml
    volumes:
      - ./configs:/configs:ro
      - ./data:/data:ro
  tremor:
    image: tremor-runtime
    depends_on:
      - kafka
    ports:
      - 9898:9898
    environment:
      - SLEEP=20
      - CONFIG_FILE=/configs/tremor-demo.yaml
      - LOGGER_FILE=/configs/logger.yaml
    volumes:
      - ./configs:/configs:ro
      - ./logs:/logs:rw
