onramp:
  - id: in
    type: file
    config:
      source: {in}
      close_on_done: true

offramp:
  - id: out
    type: file
    config:
      file: {out}

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: r
        op: runtime::tremor
        config:
          script: |
            match event of
              case %{short_message ~= glob|*INFO*|} => let $class = "info", let $rate = 2
              case %{short_message ~= glob|*ERROR*|} => let $class = "error", let $rate = 3
              default => let $m = event.short_message
            end;
            event;
      - id: b
        op: grouper::bucket
    links:
      in: [ r ]
      r: [ b ]
      b: [ out ]

binding:
  - id: test
    links:
      '/onramp/in/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/out/{instance}/in' ]
