onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - op::set:
          var: classification
          val: test
      - op::into_var:
          key: 'log_level'
          var: 'dimensions'
      - grouper::bucket:
          buckets:
            test:
              rate: 1
      - render::json
      - offramp::file:
          file: {out}
