test:
  stage: test
  image: rust:1.30
  when: always
  cache:
    paths:
      - target/
      - ~/.cargo/
  tags:
    - docker
  script:
    - apt update
    - apt-get -y install gnuplot
    - rustup update
    - rustup install nightly
    - rustup component add clippy-preview --toolchain=nightly
    - CARGO_TARGET_DIR=target.clippy cargo +nightly clippy
    - cargo test
