onramps:
  - onramp::blaster:
      source: ./data/data.json.xz
      interval: 4000000 # 250 events/s
      pipeline: main

pipelines:
  - name: main
    steps:
      - offramp::kafka:
          brokers:
            - kafka:9092
          topic: demo
