onramps:
  - onramp::kafka:
      pipeline: main
      group_id: demo
      topics:
        - demo
      brokers:
        - kafka:9092

pipelines:
  - name: main
    steps:
      - parse::json
      - classifier::json:
          rules:
            - class: 'info'
              rule: 'short_message:"info"'
            - class: 'error'
              rule: 'short_message:"ERROR"'
      - grouper::bucket:
           buckets:
            - class: 'info'
              rate: 10
            - class: 'error'
              rate: 100
            - class: 'default'
              rate: 90
      - render::json
      - offramp::debug
