onramps:
  - onramp::kafka:
      name: kafka
      pipeline: main
      group-id: demo
      topics:
        - demo
      brokers:
        - kafka:9092

pipelines:
  - name: main
    steps:
      - parse::json
      - classifier::json:
          rules:
            - class: 'info'
              rule: 'short_message="info"'
            - class: 'info'
              rule: 'short_message="INFO"'
            - class: 'error'
              rule: 'short_message="ERROR"'
      - op::into_var:
          key: 'application'
          var: 'dimensions'
      - grouper::bucket:
           buckets:
            info:
              rate: 10
            error:
              rate: 100
            default:
              rate: 90
      - op::into_var:
          key: wf_index_type
          var: 'index'
      - op::into_var:
          key: type
          var: 'doc-type'
      - render::json
      - offramp::elastic:
          endpoints:
            - "http://elastic:9200"
          batch_size: 1100
          concurrency: 5
          outputs:
            - offramp::stdout:
		prefix: '[OVERLOAD] '
