onramps:
  - onramp::kafka:
      name: kafka
      pipeline: main
      group_id: demo
      topics:
        - demo
      brokers:
        - kafka:9092

pipelines:
  - name: main
    steps:
      - parse::json
      - classifier::json:
          rules:
            - class: 'info'
              rule: 'short_message="info"'
            - class: 'info'
              rule: 'short_message="INFO"'
            - class: 'error'
              rule: 'short_message="ERROR"'
      - op::into_var:
          key: 'application'
          var: 'dimensions'
      - grouper::bucket:
           buckets:
            info:
              rate: 10
            error:
              rate: 100
            default:
              rate: 90
      - op::into_var:
          key: index_type
          var: 'index'
          required: true
      - op::into_var:
          key: index_type
          var: 'doc-type'
          required: true
      - render::json
      - offramp::elastic:
          endpoints:
            - "http://elastic:9200"
          batch_size: 1100
          concurrency: 5
          outputs:
            -
              - offramp::stdout:
                  prefix: '[OVERLOAD] '
