onramps:
  - onramp::file:
      file: {in}
      pipeline: main

pipelines:
  - name: main
    steps:
      - parse::json
      - classifier::mimir
      - grouper::bucket
      - render::json
      - offramp::file:
          file: {out}
